src/main/java/htmlpublisher/HtmlPublisherTarget.java
src/main/resources/htmlpublisher/HtmlPublisher/config.jelly
src/main/resources/htmlpublisher/HtmlPublisher/help.html
src/test/groovy/htmlpublisher/HtmlPublisherTest.groovy

Contributes to JENKINS-24057
Possibly fixes JENKINS-11689 and JENKINS-5682
I added an option to an HTML report to always link to the latest build instead of the latest successful link. Default behaviour is like before to link to the latest successful build if the "Keep past HTML reports" is selected. 
I also added a help.html to describe the behaviour of the HTML publisher. I partly copied the Wiki description for this and added a description for the "Allow missing report" option and the new "Always link to last build job page" option.

JENKINS-24057: Allow job level links to last instead of last successful build

---

src/main/resources/htmlpublisher/HtmlPublisher/config.jelly
src/main/resources/htmlpublisher/HtmlPublisherTarget/config.jelly
src/main/resources/htmlpublisher/HtmlPublisherTarget/config.properties
src/main/resources/htmlpublisher/HtmlPublisherTarget/help-allowMissing.html
src/main/resources/htmlpublisher/HtmlPublisherTarget/help-alwaysLinkToLastBuild.html
src/main/resources/htmlpublisher/HtmlPublisherTarget/help-keepAll.html
src/main/resources/htmlpublisher/HtmlPublisherTarget/help-reportDir.html
src/main/resources/htmlpublisher/HtmlPublisherTarget/help-reportFiles.html
src/main/resources/htmlpublisher/HtmlPublisherTarget/help-reportName.html
src/main/resources/htmlpublisher/lib/repeatableProperty.jelly

https://issues.jenkins-ci.org/browse/JENKINS-29635
The original UI is very useful for small reports located in paths near the workspace. However, for long paths the interface is not comfortable due to small input windows.
I propose to migrate the UI to the classic Jenkins approach:
* vertical layout of controls with enough space for long directory paths
* help panels with additional info for users
* storage of UI controls within the HTMLPublisherTarget class
* usage of standard Jenkins controls => the plugin will be more tolerant against the ongoing rework of Jenkins core UIs
Current layout:
Proposed layout (with expanded "Advanced" section):
@reviewbybees @mrooney

[JENKINS-29635] - Rework the configuration page of the HTML Publisher

---

pom.xml
src/main/java/htmlpublisher/HtmlPublisher.java
src/main/java/htmlpublisher/HtmlPublisherTarget.java
src/main/java/htmlpublisher/workflow/PublishHTMLStep.java
src/main/java/htmlpublisher/workflow/PublishHTMLStepExecution.java
src/main/java/htmlpublisher/workflow/WorkflowActionsFactory.java
src/main/resources/htmlpublisher/workflow/PublishHTMLStep/config.jelly
src/test/java/htmlpublisher/workflow/PublishHTMLStepTest.java

The change adds a Workflow step, which allows to publish HTML reports

[JENKINS-26343] - Workflow Integration

---

src/main/java/htmlpublisher/HtmlPublisher.java

Thanks for this useful plugin.
When configuring the plugin on the admin UI we can list multiple index pages separated by a comma, for instance:
page1.html,page2.html,page3.html
However we do not seem to be able to use [FileSet includes](http://ant.apache.org/manual/Types/fileset.html), for instance:
*.html
FileSet includes are quite handy and seem to be used in many places in core Jenkins and plugins (for instance they are used in the [JUnit plugin](https://github.com/jenkinsci/junit-plugin)).
Why not support them ? Here is a pull request with a proposed changeset.

Select index pages using FileSet includes.

---

src/main/java/htmlpublisher/HtmlPublisherTarget.java

When archiving multiple HTML reports per build, and accessing them through the project-level links, false-positive checksum mismatch errors appeared because the actions used whatever was the first report as reference.
Not as well tested as I'd like due to time constraints, but I wanted to get a possible fix to this issue out ASAP.
My apologies to @mrooney for introducing this boneheaded bug.
@reviewbybees

[FIX JENKINS-32281] Consider multiple reports per build

---

src/main/java/htmlpublisher/HtmlPublisher.java
src/main/java/htmlpublisher/HtmlPublisherTarget.java
src/main/resources/htmlpublisher/HtmlPublisherTarget/config.jelly
src/main/resources/htmlpublisher/HtmlPublisherTarget/config.properties
src/test/groovy/htmlpublisher/HtmlPublisherTest.groovy

We want to archive a html file builds/blah.html, but found out all the contents of builds folder were also copied from slave to master, I think add an include pattern will fix the issue.
The change is backward compatible

Allow user to set file includes pattern

---

src/main/java/htmlpublisher/HtmlPublisherTarget.java
src/test/groovy/htmlpublisher/HtmlPublisherIntegrationTest.groovy
src/test/java/htmlpublisher/HtmlPublisherTest.java

Report Name, directory, files, and titles are now all trimmed. Note that
trimming is only done when configuration is saved.

Fix JENKINS-47034

---

src/main/java/htmlpublisher/HtmlPublisherTarget.java
src/main/resources/htmlpublisher/HtmlPublisherTarget/BaseHTMLAction/index.groovy

When viewing HTML Report connected to build it is convenient to be
able to use "Back To ..." option to return to build not to the project.
This commit adds additional methods to BaseHTMLAction and overrides in
HTMLBuildAction. Thanks to that we can easily go back to project or to
build accordingly.
Signed-off-by: Artur Harasimiuk <artur.harasimiuk@intel.com>

adding backToName and backToUrl variables

---

src/main/resources/htmlpublisher/HtmlPublisher/header.html

When you have many tabs in your HTML reports, they start to overlap. This simple fix makes them more user-friendly while keeping preferred "inline" bahaviour.

fix display issues for many tabs

---

src/main/java/htmlpublisher/HtmlPublisher.java
src/test/java/htmlpublisher/HtmlPublisherIntegrationTest.java

Reverts jenkinsci/htmlpublisher-plugin#43
Unfortunately the changes made to support Ant style wildcards only work if the job is being run on the Jenkins master and won't work if it is running on a remote agent. The Ant style wildcard logic will hopefully return soon if the remoting logic can be fixed.

Revert "Enable use of Ant style wildcards for index files"

---

src/main/java/htmlpublisher/HtmlPublisher.java
src/main/java/htmlpublisher/HtmlPublisherTarget.java
src/test/java/htmlpublisher/HtmlPublisherIntegrationTest.java

Rework work done before (see https://github.com/jenkinsci/htmlpublisher-plugin/pull/43) to work in an environment that has workloads running on agents. 
@carlosgv87 as the previous PR submitter, would be good to get you to check out this PR just to make sure that I haven't missed anything that you've done previously in my Git'ing around.

Enable use of Ant style wildcards for index files

---

Jenkinsfile
pom.xml
src/main/java/htmlpublisher/HtmlPublisher.java

Change HTML Publisher to be baselined off of 2.150.3 as the majority of users are now using this version or above. 
As part of this change this also means a switch to Java 8 building and also it incorporates the http to https switch originally proposed by @daniel-beck in https://github.com/jenkinsci/htmlpublisher-plugin/pull/46 (plus http-to-https-ifies the other URLs too).

Increment minimum versions

---

pom.xml
src/main/java/htmlpublisher/HtmlPublisherTarget.java
src/test/java/htmlpublisher/HtmlPublisherIntegrationTest.java
src/test/java/htmlpublisher/HtmlPublisherTest.java

Currently build actions are added only and so, if the same action is called multiple times, multiple build actions appear in the navigation. This change is to make a subsequent call replace the previously created action.

Switch to adding or replacing build action

---

pom.xml

Despite #42 it seems this was obsolete since #32 which actually deleted Groovy tests.

Delete unused gmavenplus-plugin

---

pom.xml
src/main/java/htmlpublisher/HtmlPublisherTarget.java
src/test/java/htmlpublisher/HtmlPublisherIntegrationTest.java
src/test/java/htmlpublisher/HtmlPublisherTest.java

This reverts commit 2360af32e5794374bc2b29c8752a9d24f13159b5.
The new functionality just didn't work and caused more problems than it was attempting to solve.

Revert "Switch to adding or replacing build action"

---

src/main/resources/htmlpublisher/HtmlPublisher/header.html
src/test/java/htmlpublisher/HtmlFileNameTest.java

The file name could contain URL unsafe characters, when used to construct 'src' attribute of the iframe, it must be URL
encoded.

[JENKINS-65028] URL encode the html file name

---

src/main/resources/htmlpublisher/HtmlPublisher/header.html
src/test/java/htmlpublisher/HtmlFileNameTest.java

The html filename may contain subdirs with slashes. Since v1.26 the slashes are encoded as %2F.
These slashes should not be html encoded but remain as slashes in the 'src' attribute of the iframe.
This behavior has been introduced with PR https://github.com/jenkinsci/htmlpublisher-plugin/pull/108.
See also [JENKINS-65028](https://issues.jenkins.io/browse/JENKINS-65028) and [JENKINS-66929](https://issues.jenkins.io/browse/JENKINS-66929)

Fixed handling of slashes in html filename (JENKINS-66929)

---

src/main/resources/htmlpublisher/HtmlPublisher/header.html
src/test/java/htmlpublisher/HtmlFileNameTest.java

`replace('%2F', '/')` would only replace the first occurrence of `%2F` with a slash, resulting in broken relative links on pages whose paths contain multiple slashes.
Discussion: https://github.com/jenkinsci/htmlpublisher-plugin/pull/138/commits/5c02afab96343c128ae5df8da4bbe9dbdd3cd616#r746408830

Bugfix: Replace all occurrences of %2F with slashes in file names

---

Jenkinsfile
pom.xml

Java 21 was released Sep 19, 2023. We want to announce full support for Java 21 in early October and would like the most used plugins to be compiled and tested with Java 21.
The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
The change intentionally tests only two Java configurations, Java 17 and Java 21 because we believe that the risk of a regression that only affects Java 11 is shallow. We generate Java 11 byte code with the Java 17 and the Java 21 builds, so we're already testing Java 11 byte code.
Testing done
===
Confirmed tests pass with Java 21.
Supersedes pull request: #259.
Supersedes pull request: #260.
- ~~Link to relevant …

Update parent POM, update BOM, test with Java 21

---

pom.xml

jenkinsci/htmlpublisher-plugin@6b840248dd0d691bbac9b515cd750b3f925909b2 started bundling the following unnecessary JARs into the plugin JPI:
```
[INFO] Bundling direct dependency access-modifier-annotation-1.33.jar
[INFO] Bundling direct dependency access-modifier-suppressions-1.33.jar
```
Verified the JARs are no longer bundled during a plugin build.

Remove unnecessary JARs from JPI

---

src/main/resources/htmlpublisher/HtmlPublisher/footer.html
src/main/resources/htmlpublisher/HtmlPublisher/header.html

Currently, the plugin shows double scrollbars.
https://github.com/jenkinsci/htmlpublisher-plugin/assets/1770529/dc6cd608-3daa-4f85-9dcc-e05f3bb7bde0
I found that it was fixed in #3 but re-introduced in #39.
While keeping in mind the multi-tab support, I changed the logic behind iframe height calculation a bit and forced the host page to hide its scrollbars (otherwise the host's scrollbar will show and hide on every resize).
https://github.com/jenkinsci/htmlpublisher-plugin/assets/1770529/28d2334e-761e-45d9-b027-2be3ff3970ca

fix: properly stretch iframe to all available space

---

pom.xml
src/main/java/htmlpublisher/HtmlPublisher.java

So that a Jenkins installation which is 100% Pipeline can not bother having this plugin installed. Amends 6204dbf85178ec951af0dfefc088d93fe451ac1e. The purported fix seems very suspect to me (`Item.onLoad` should be called only by Jenkins core, not in this context) and there is no regression test so I am half inclined just to delete it.

Make dep on `matrix-project` optional

---

src/main/java/htmlpublisher/HtmlPublisher.java
src/main/resources/htmlpublisher/HtmlPublisher/header.html
src/main/resources/htmlpublisher/HtmlPublisherTarget/BaseHTMLAction/index.groovy
src/main/webapp/js/htmlpublisher.js

https://issues.jenkins.io/browse/JENKINS-74015
https://issues.jenkins.io/browse/JENKINS-74746
There are two ways that generated HTML reports are rendered. Which mode is used is controlled by `useWrapperFileDirectly` flag. The HTML report is generated during the build step and is saved in `jobs/JOB_NAME/builds/BUILD_NUMBER/htmlreports` directory. If `useWrapperFileDirectly` flag is set to true then the file generated during the build step will be served directly. If the flag is false then [this code](https://github.com/jenkinsci/htmlpublisher-plugin/blob/9eb828375acb84f4c4a20e9c0ad68a12a49ef094/src/main/resources/htmlpublisher/HtmlPublisherTarget/BaseHTMLAction/index.groovy#L30-L38) reads the report file and extracts pieces of data that are inside the `li` tags and then few lines below …

[JENKINS-74015][JENKINS-74746] Improve CSP compatibility

---

pom.xml

Bridge methods were being defined but not actually created because the bridge method injector was not being executed at build time.
Comparing the output of `javap -c './target/classes/htmlpublisher/HtmlPublisherTarget$HTMLPublishedForProjectMarkerAction.class'` before and after this PR:
```
--- /tmp/old    2024-03-11 15:04:01.355304753 -0700
+++ /tmp/new    2024-03-11 15:14:33.404180689 -0700
@@ -37,4 +37,14 @@
0: aload_0
1: getfield      #7                  // Field actualHtmlPublisherTarget:Lhtmlpublisher/HtmlPublisherTarget;
4: areturn
+
+  public final hudson.model.AbstractBuild getOwner();
+    Code:
+       0: aload_0
+       1: aload_0
+       2: invokevirtual #67                 // Method getOwner:()Lhudson/model/Run;
+       5: ldc           #17                 // class …
```

Create bridge methods

---

README.md
src/main/java/htmlpublisher/HtmlPublisherTarget.java
src/main/resources/htmlpublisher/HtmlPublisherTarget/config.jelly
src/main/resources/htmlpublisher/HtmlPublisherTarget/config.properties
src/main/resources/htmlpublisher/HtmlPublisherTarget/help-icon.html
src/test/java/htmlpublisher/HtmlPublisherIntegrationTest.java

Inspired by https://github.com/jenkinsci/htmlpublisher-plugin/pull/277 (that was most likely abandoned)
And ensure it support custom `symbol`
Interactive tests with freestyle job with both image from report and symbol 
**With symbol**
**With image from report**

Add support for icon on sidebar report action

---

src/main/java/htmlpublisher/HtmlPublisherTarget.java
src/test/java/htmlpublisher/workflow/PublishHTMLStepTest.java

This PR fixes [Jira issue 75392](https://issues.jenkins.io/browse/JENKINS-75392) by proposing a simple additional check to the existence of the icon file path inserted.
**Setting the icon with a non-existing path**
**Before**
**Now**

Add improvement for icon on sidebar report action

---

src/main/java/htmlpublisher/HtmlPublisher.java

When publishing an HTML report and the directory is missing but the report options have allowMissing set, the output to the user in the build log written as an error.
This change only outputs an error message when allowMissing is not set; otherwise, a more informational message will be displayed.
Run a simple freestyle job with two missing reports configured: one that is allowed missing, and the other that doesn't allow for missing reports and read the job output.

Reduce log severity for missing directories when allowMissing is set
